language: python

python:
- '3.5'

install: make install

script: make test

deploy:
  provider: pypi
  user: datacamp
  password:
    secure: O6JATq7MoN0/NrraykJWhXsabWpNomLe2xjwbSNkdDgjevzchHJV1qODcrEHlKuLzQ8Z9DKk5E4A/hU5SRfHKaJuTrhIH9L+Urno4pO2Bgzz8M5LXF5+jJXmvbC6q+bLJ9VrQ8ITqh0QLH3aI4ZkW0ohISxXW5wVHtdrGiFcCvoQMcjqwTlLqaCfvf8JKjl1tVu/Bz/gLmUFMLeYo6zkbgzVvoIINWzbsQ9XPoXdw45CeyIUkVCc8kUiX65UUcnyuOJ5La/fOXPoR7T6h2TFlShIbcVx7Tt6lnWyxwR+rEE9u70m90l/Lho/LNaFiXvH7li6b+p21U+8K+srP6awsE/ePpnshxlL9InahPolcR5ynKE79J47IcDqYNpIW255v6WUvQmKE8BqtRAjfYK1Zy5Zyvh6RfHihScRjcv45zcSz8eTqXwH6B+7n+A84eRrMLpSKyr9rWhnhGN8Ac1fMnhfx94FnVFrzS7I4uDiI/QQL8I2YgVJF9jbuOA3bg7ZayocEnGcSbUuD04e9fWZYCeTy8OLSw7GDuEtpRvBKzB7GhKeZmXkCVu8tzyVlIXpoQoxnmJwZE4zAZ31pnadMBSLJ7Opb/EgiHqsg7GaBD7anQuIgNLycqpW2DkrPMDVAcsrmLMV7hs+idmi/ewslYr9mYZsW/ztDWfLdWFwOhs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/sqlwhat-ext
  skip_upload_docs: true
